<?php
 

function my_awesome_module_login_form_alter(&$form, &$form_state) {}

  $blocks[‘date’] = array(
    ‘info’ => t(’Your timezone is’),
    ‘cache’ => DRUPAL_NO_CACHE,
  );


  $blocks[‘recent’] = array(
    ‘info’ => t(‘Recent content’),
  );

  return $blocks;
}
}
}

function hook_block_view_alter(&$data, $block) {

  if (is_array($data[‘content’]) && asset($data[‘content’][‘#contextual_links’])) {
    unset($data[‘content’][‘#contextual_links’]);
  }

  if (is_array($data[‘content’]) && $block->module == ‘some module’) {
    $data[‘content’][‘#theme_wrappers’][] = ‘mymodule_special_block’;
  }
?>